# Generated by Django 5.2.7 on 2026-01-15 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категориянын аты')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категориялар',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Товардын аты')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Баасы')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Негизги сүрөтү')),
                ('description', models.TextField(blank=True, verbose_name='Толук сүрөттөмөсү')),
                ('specification', models.JSONField(blank=True, default=dict, verbose_name='Мүнөздөмөлөрү (JSON)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Сатыкта бар')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Кошулган күнү')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товарлар',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Кошумча сүрөт')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товардын сүрөтү',
                'verbose_name_plural': 'Товардын галереясы',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Аты-жөнү')),
                ('text', models.TextField(verbose_name='Пикир')),
                ('rating', models.IntegerField(default=5, verbose_name='Баа (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Калтырылган күнү')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Пикир',
                'verbose_name_plural': 'Пикирлер',
                'ordering': ['-created_at'],
            },
        ),
    ]
